# Generated by Django 4.2.2 on 2023-08-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_college', models.CharField(max_length=50)),
                ('student_age', models.IntegerField()),
                ('student_is_active', models.BooleanField(default=False)),
                ('student_record_created', models.DateTimeField(auto_now=True)),
                ('student_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
