# Generated by Django 4.2.2 on 2023-08-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_address', models.CharField(max_length=50)),
                ('employee_email', models.CharField(max_length=50)),
                ('employee_phone', models.IntegerField()),
                ('employee_working', models.BooleanField(default=False)),
                ('employee_department', models.CharField(max_length=50)),
                ('employee_record_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
